# Generated by Django 4.0.6 on 2022-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='city',
        ),
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
