# Generated by Django 4.0.6 on 2022-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_car_city_remove_car_state_booking_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='book',
        ),
        migrations.AddField(
            model_name='booking',
            name='To_agree',
            field=models.BooleanField(default=False, verbose_name='Car is Booked'),
        ),
    ]
